#how to deploy a xml action file for github https://myridia.com/dev_posts/reply/3904
name: Publish to Wordpress via SVN
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Publish to Wordpress via SVN
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      run: |
        echo "hello"
        
